# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


User.create!(username:"AMF",password:"password",fname:"Mandy",lname:"Fielding",gender:"female",dob:DateTime.new(1987, 3, 10),email:"amandamfielding@gmail.com",phone_number:"209-614-5459",tips_cert:true, vis_tats:true, valid_dl:true, admin:true, company_id: 1)
User.create!(username:"lew",password:"123456",fname:"Lindsey",lname:"Whitley",gender:"female",dob:DateTime.new(1992, 12, 5),email:"lewhitley@gmail.com",phone_number:"714-343-0605", valid_dl:true, admin:true, company_id: 2)

Company.create!(name:"Cerda Productions",description:"event staffing")
Company.create!(name:"Dream a Little Dream Events",description:"event planning", website_url: "http://www.dreamalittledreamevents.com/")

Event.create!(admin_id:1,title:"Outside Lands",lat:0,lng:0,city:"San Francisco",state:"CA",description:"concert in the city",pay:500,pay_freq:"day",start_date:DateTime.new(2016, 12, 27),end_date:DateTime.new(2016, 12, 28))
Event.create!(admin_id:2,title:"Cooney Wedding",lat: 34.2172, lng: 119.0180, city: "Camarillo", state: "CA", event_type: "wedding", description: "https://cooneytoons.com", pay: 14, pay_freq: "per hour", start_date:DateTime.new(2017, 1, 14), end_date:DateTime.new(2017, 1, 14))
Event.create!(admin_id:2,title:"Adam and Steve's Wedding",lat:37.7793, lng:122.4188, city: "San Francisco", state: "CA", event_type: "wedding", description: "A beautiful wedding in City Hall", pay: 17, pay_freq: "per hour", start_date:DateTime.new(2017, 1, 1), end_date:DateTime.new(2017, 1, 1))
Event.create!(admin_id:2,title:"Gusto Banquet",lat:38.2085, lng:122.4518, city: "Sonoma", state: "CA", event_type: "banquet", description: "Start-up's end of the year celebration", pay: 15, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 20), end_date:DateTime.new(2016, 12, 20))
Event.create!(admin_id:2,title:"Heather and John's Wedding",lat:38.5021, lng:122.4643, city: "Saint Helena", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 15, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 24), end_date:DateTime.new(2016, 12, 24))
Event.create!(admin_id:2,title:"Graham and Isla's Wedding",lat:37.8143, lng:122.2672, city: "Oakland", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 13, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 27), end_date:DateTime.new(2016, 12, 27))
Event.create!(admin_id:2,title:"Jefferson Wedding",lat:0, lng:0, city: "Monterey", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 16, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 27), end_date:DateTime.new(2016, 12, 27))
Event.create!(admin_id:2,title:"Watson Wedding",lat:0, lng:0, city: "San Francisco", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 16, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 27), end_date:DateTime.new(2016, 12, 27))
Event.create!(admin_id:2,title:"Frederick Wedding",lat:0, lng:0, city: "San Francisco", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 13, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 31), end_date:DateTime.new(2016, 12, 31))
Event.create!(admin_id:2,title:"Chemistry Graduation Party",lat:0, lng:0, city: "Berkeley", state: "CA", event_type: "private party", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 18, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 31), end_date:DateTime.new(2016, 12, 31))
Event.create!(admin_id:2,title:"Holiday Party",lat:0, lng:0, city: "Berkeley", state: "CA", event_type: "private party", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 18, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 26), end_date:DateTime.new(2016, 12, 26))
Event.create!(admin_id:2,title:"Janine and Christian's Wedding",lat:0, lng:0, city: "Berkeley", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 15, pay_freq: "per hour", start_date:DateTime.new(2016, 12, 26), end_date:DateTime.new(2016, 12, 26))
Event.create!(admin_id:2,title:"Peabody Wedding",lat:0, lng:0, city: "San Francisco", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 400, pay_freq: "per event", start_date:DateTime.new(2016, 12, 31), end_date:DateTime.new(2016, 12, 31))
Event.create!(admin_id:2,title:"Linda and Terry's Wedding",lat:0, lng:0, city: "San Francisco", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 400, pay_freq: "per event", start_date:DateTime.new(2017, 1, 7), end_date:DateTime.new(2017, 1, 7))
Event.create!(admin_id:2,title:"Joe and Elaine's Wedding",lat:38.4932, lng:122.7238, city: "Santa Rosa", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 400, pay_freq: "per event", start_date:DateTime.new(2017, 1, 7), end_date:DateTime.new(2017, 1, 7))
Event.create!(admin_id:2,title:"Paul and Christine's Wedding",lat:38.2967, lng:122.4583, city: "Sonoma", state: "CA", event_type: "wedding", description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", pay: 400, pay_freq: "per event", start_date:DateTime.new(2017, 1, 7), end_date:DateTime.new(2017, 1, 7))
